 

= 100 dagar av trålande

= Dag 1

Vi hade inte en susning, när vi plockade upp
damen i sjönöd, att det skulle bli så här. Men
vad ska man göra? En riktig man reder sig
själv, säger kapten. Vi sparar tonfisken till sist,
då det är så rikt på magnesium, vilket torde
mota eventuell skörbjugg i grind.

Med kaptenens ord:
Nu här det av, för fulla segel

med lärdomar från Marx och Hegel

Om vi bara hade haft WiFi.

= Dag 2

Den stora fördelen med att ha kastat ankar är
att vi inte längre är bundna till
"landkrabbornas” konventioner och förmätna
regler kring hur, vad, vem och varför. Här
finns bara ett när.

Jag hoppas kunna försjunka i vågspelet som
naturen bjuder på. Men det finns arbete att
göra samtidigt. Jag vet inte om jag kommer att
bli sjösjuk, till exempel. Det är väl bara att
hålla käft och hålla in det som vill ut, vare sig
det gäller spya eller känslor. Tur att jag har dig
dagboken, min fasta punkt i tillvaron.
Dag 3

Vi ska aldrig gå i land. Det är det senaste budet.
Senti går hamnade min sparkcykel över däck, i
ett vansinnesutbrott från en kapten som inte
fick sin berättigade andel skönhetssömn.

Jag saknar att cykla så mycket. Nils säger att
det är för danskar, att jag inte ska komma här

och komma.

Måste spara på bläcket.

= Dag 4

Har kommit på kant med kapten. Eller det är
väl i underkant — jag vet inte om jag klarar av
mycket mer vrålande, känner mig osäker om
jag kommer att kunna ta en utskällning till.

Tydligen skapas en assonans mellan ordet
kapten och efternamnet på min kapten, Nils,
Nils Langlet. För att göra det tydligt så kan
man ju stava det så här: Nils Langlét. Men det
gör han lika lite som kapten stavas kaptén.
Jag borde ha vetat bättre, det är underförstått
— liksom trålandet.

= Dag 5

Tålamodet sträcker sig ända upp i himlen,
genom molnen som då och då kastar en
soldränkt D-vitamin-pelare rakti plytet. Vissa
vill inte sola, det änns ingen tid för det.

Lugnet har lagt sig runt vår trål som en spådam
berör sin kristallkula. Vi spelade rummy och
låtsades att vi var karaktärer från Ankeborg,
Nils vann. Det var han som lärde oss
kortspelet. I morgon har jag och skepparen
bestämt oss för att spela Jenga. Men det är en
hemlighet. Man vet aldrig när tornet rasar.
Dag 6

Långt i fjärran syns en skidbacke, men ingen
snö, för det är sommar, vilket märks på rostens
karaktär när vi rullar upp mastodontkedjan
som, liksom ankaret, drar med massa slam
upp på land.

"Du behöver ingen utbildning för att slicka
röv”, sa Nils, och jag äck ingen vidare hjälp att
göra rent den äckliga metallen från havets
bottenskikt.

= Dag 7

Nils har vrålat på mig för tredje gången. Redan
nu. Sånt där avgrundsvrål. "Hur fan i hela
hel-vetet har du glömt ta med osthyveln!”

Vad svarar man på det? Pizzaskäraren kom i
alla fall med. Jag var mest förvånad över att
han upptäckte det nu en vecka senare. Vi hari
och för sig haft annan mat fram tills nu utöver
mackor.

= Dag 8

Margaretas solblekta hår har salti sig. Jag är så
sugen. Men se men inte röra. Jag är en matros
och ska inte tro att jag är något. Som en god
middag med besk eftersmak. Det är jag.

Någon har ryckt ut sidor ur mina böcker. Jag
har mina misstankar.

= Dag 9

Om vi bara hade haft WiFi... så hade jag
kunnat spänna av från trycket och pressen.

Vi äro hantlangare och lakejer för ett stort
världsankare, tydligen; kaptenen blir "tydligare
och tydligare” allt eftersom jag och andra inte
reder oss själva i tillräcklig grad. I ett försök att
skapa tilltro frågade jag om hur det kom sig att
det blev en trål, i stället för en oljepråm, eller
ett kryssningsfartyg. Kaptenen tittade på mig
som man ser på en ojordad stickkontakt, och
svarade att det kan jag väl fråga Poeten från
Buenos Aires hamn? Jag vet inte vad han
menade, men vet honom vara säker på sin sak.

= Dag 10

Förresten är det inte så att kaptenen är en dålig
människa, det är jag som är en "dålig
skeppare”. Jag ska göra mitt yttersta för att inte
komma på kant något mer, eller göra något
annat som undergräver det stora uppdraget.

Nils talade häromdagen i svepande termer,
storögt, om ett världsankare som styr oss på
färden mot en bättre hamn. Jag såg ungdomen
i hans vindpinade anlete lysa upp som ett
magiskt Atlantis skimrar i drömmarna jag har
om nätterna, där jag talar änska och dansar
barfota med Margareta, som då heter Mary.

= Dag 11

om vi bara hade haft WiFi. Då hade jag
kunnat ringa hem och läsa nyheterna. Jag
undrar så mycket hur det går för Djurgården,
och för Socialdemokraterna. Jag är nyäken på
hur det ser ut med Systembolagets sortiment,
änns där måhända några nyheter.

= Dag 12

Jag hinner inte skriva nu — måste hjälpa till och
göra Nils nöjd inför morgondagens stora
Landstigning! Hoppas Margareta ser mig för
den jag är, eller som jag ser henne, som en
dröm för mig att känna att jag lever av att
drömma, som en t"å1 blir en trål av att ha ett
hav att färdas i, vågor att bryta, utan det hade
inte en båt varit en trål, även om det hetat trål,
och på samma sätt hade inte jag varit en
skeppare om inte Margareta kan ge mig en
blick eller två som berättar för mig på samma
sätt som man vet någoti en dröm att jag änns
och är den jag är här på Trålaren som ju, det
måste påpekas även om det är lite stressigt, ska
lägga till i morgon som en dröm lägger an till

= Dag 13

Fy fan. Landstigning då. Egentligen borde eller
skulle det kännas som en lättnad, att äntligen
vara på fast land, fast punkt. Raka vägen
genom Lettland via Daugava. Tro fan att
Larsson stod i hamnen. Jag gick in i min hytt
igen. Det föll sig naturligt, plötsligt ett bättre
val att stanna ombord här och försöka spä på
känslan av hem som ändå uppstått under de
fjorton långa årlika dagarna jag hittills hunnit
tillägna tjänstgöringen.

= Dag 14

Jag har glömt att berätta vilka vi är på trålen.

= Dag 15

Nu är Larsson på trålen. Hoppas han inte åker
med när vi lägger uti morgon. Men först och
främst får jag inte låta det röra mig ryggen. I
kväll är min sista kväll på land, i samhället, på
lång tid framöver och jag har lyckats tvätta
bort surströmmingen från bakom öronen, satt
på mig frack och hög hatt. Här ska det rumlas.

= Dag 16 

Man underbord! Skrek jag. Det var inget roligt
skämt. Nu sitter jag i isoleringskarantän,

kedj ad mellan fyra lådor finska örtdroppar
som ska levereras till Rotterdam, för att sedan
tas om hand av ett annat fartyg. Vilka som
beställt all Carmolis vet jag inte, vågar inte
fråga, kan inte morse.

 
= Dag 17

Jag hör hur de talar där uppe, med trevliga
toner, uppsluppna som fåglar på en
telefonledning. Det verkar som att Larsson har
tagit min plats. Det är han som borde äta
vatten och bröd.

Jag får inte borsta tänderna. Men det är jag
nästan glad för, då jag har kvar lakritssmaken
från mitt besök på konfektyrbutiken nära stora
torget i Daugavpils.

= Dag 18

Brus på radion. Brus från radion. Osäker om
det är någon som försöker kommunicera eller
om radion med tillhörande ljudsystem från
Blaupunkt bara vill jävlas. Vore ju dummare än
dumt att stänga av den.

Kaptenen blev syrlig när han blev varse att jag
inte behärskar morse. Känner mig som en
usling, men samtidigt, hur skulle jag kunna
morse, när kaptenen Vägrar lära ut morse?

"Pedagogik är för fastlandsklåpare och det här
är ingen jävla vattenburen skola.” Nähä.

= Dag 19

Haft radion avstängd hela dagen. Blev knäpp

av bruset som kom i stötar. Som att jag nästan
började höra saker som inte fanns där. Den
frigjorda energin som kom av radiobrusets
frånvaro gjorde att jag kom på hur Nils skulle
bli nöjd! En osthyvel, gjord av ett
konservburkslock och en trasig skiftnyckel. Ska
visa för honom imorgon.

= Dag 20

Rotterdam är en tudelad hamn i gängse
världsbild — på ett sätt ett nav för handel och
fred, och samtidigt ett ogästvänligt ställe för
världens gröngölingar. Det har jag fått höra,
liksom mina äskar varma.

Osthyveln gick hem. Radioavstängningen inte
lika mycket. Fick en rejäl avhyvling av kapten,
som för övrigt är den enda av oss alla som har
galonkläder.

= Dag 21

Jag bad om en flytväst. "Det är bättre med bly
innanför västen”, svarade kapten... Till havs
när inget fackförbund, ty kaosteorin råder ej.
Här är det ordning och reda som gäller, som i
ett solsystem. Min själ är ett svart hål. Hittar
inte mina blyertspennor.

 
= Dag 22

Först var det sparkcykeln, som gjorde för
mycket oljud om nätterna för att den skulle få
vistas på däck, som slängdes överbord.

Nu senaste var det osthyveln.

"Du kan ju för helvete inte hyvla smör med en
konservburk och en skiftnyckel”, sa Nils, till
synes helt obrydd om att jag hade surrat/tejpat
samman dem med hårstrån/eltejp.

Jag hade ju kunnat använda den själv, till att
hyvla den goda osten som jag är så sugen på.

= Dag 23

Känns som vi inte har makten längre. Försöker
tråla enligt konstens alla regleri Mälaren, men
nu steg Nils Langlet i land i Buenos Aires, fast
besluten om att änna sig en flicka för aftonen.
Det vankas zumba-transcendental-orientaliskt
änskt disco, tydligen. Vi har kastat i ankaret vi
kan se, men kan inte förklara hur vi hamnade
här. Kanske stämmer myten; änns där ett
osynligt ankare som snarare än vår kaptens
koordinater bestämmer var vi lägger till. Som
om världen lägger till vid trålaren. Trålaren
styrs av ett osynligt ankare, världsankaret.
Känner frossa.

= Dag 24

Jag vill bli den trålkarlaste trålkarlen som
någonsin satt sin fot på en trålare! Men nu har
ett nytt hinder uppstått på vägen, som om det
fanns något fast, som en väg, att ta sig fram
längs och inte bara en brytpunkt mellan
himmel och helvete vari jag bara skulle mäkta
med att sjunka. Med sig från Buenos Aires
hamn hade Kapten och Larsson en Poet. Det
första han gjorde ombord var att leta in-
spiration, och fann ett råttbo. Vid den nattliga
rummyn läste Poeten lång blankrad om upp-
äten ost. Kapten påpekade, gravallvarligt, syd-
ostlig blick, att verklighet slår dikt. Osten: slut.

= Dag 25

Sj ösjuk, men inga vågor. Kapten var en gång i
Finland och talade svenska med en
välkammad änlandssvensk. Oj vad full han var.
Tror att de pratade om industri. Hangö, så
långt sydväst man kan komma i Finland. Var
på ett fartyg som gick därifrån till Läbeck med
papper. Lastbilar fulla med saker som ännar
vill ha. Grejer, mackapärer och mojänger,
komponenter, beståndsdelar och deviser. Och
åt andra hållet, papper. Det gick även under
kalla kriget. Kaptenens fraktfartyg gick från
Liibeck, fd. Västtyskland. Men då lever vi också
i den värld som är den bästa av möjliga världar.

= Dag 26

Larsson och råttorna. Var det han som drog
med dem? Är det han eller råttorna som har
ätit upp osten? Mig kvittar det av främst två
anledningar: Det var inte hans ost och han är
en råtta så sak samma! Osten är borta sedan
länge och Larsson är på trålen.

Sammanträffande? Råttor är på trålen och
Larsson klev på trålen och är på trålen.
Sammanträffande?

= Dag 27

Om äskarna hade haft ett eget Facebook — hur
hade det sett ut då? Blubb-book. Lajk—knappen
hade nog varit en mask.

Havet slukar allt — därför är det fritt fram att
slänga vadhelst överbord, vilket ter sig tydligt
av vår trålrapport. Detta förklarade kaptenen i
farten förbi Göteborgs hamn.

Trålrapport:
- En hel del äsk av alla dess slag.

= Dag 28

Prövade teorin om äskarnas Facebook på Han
som inte får nämnas vid namn, Larsson. Det
var för meta, enligt Larsson. Undrade vad jag
äskade efter. Han är ju helt bakom flötet.

Om fenomenet synvilla änns, tordes även
synbåt ännas.

= Dag 29

I dag äck jag lära mig ett nytt ord.

Krumhult (skulker's locker);

ett gömställe ombord för en trött sjöman, s.k.
"krumhultsgast".

 
= Dag 30

Det är inte bara vi längre som vet att det änns
äsk ombord. Storfåglarna vet också sedan vi
snuddat förbi en 6. Av presenning äck jag upp
en drake i skyn, likt ryssarna när de vill
konkurrera ut GPS med GLONASS. Effektivitet
O%. Trots att jag skvätt på några droppar
Carmolis.

Vilken soppa. Men sen slog det mig — trålen är
fåglarnas nya hem. De är lika fängslade nu,
som vi är, här. Lyckades få stryptag på två
Argentinska änder. Gott så! De ska tillredas, på
bästa sätt. Men utan ost. Larsson...

= Dag 31

Mary, är det inte en ödets nyck, att jag blev
rekryterad av en kapten, och du blev
rekryterad av mina drömmars djuriskt
innerliga begär; när vi nu är på samma trål
som den stora Langlet, en man jag skulle gåi
döden för, om såpass mycket stod på spel, till
exempel under den nattliga rummyn, där jag
försöker så gott jag kan, men mycket riktigt
aldrig når fram, till vinsten, till dig. Och du
faller i kaptenens arm i en stämningsfull
cha-cha-cha...

= Dag 32

Hittade en mänsklig tand i andsoppan, det var
märkligt. Gjorde ett tankeexperiment hur det
skulle vara att ha näbb. Änder har fler tänder
än man tror. Det vet man om man blivit biten
av två. Innan de brann upp i köket och äck
Aromatpuder över sig.

Poeten från Buenos Aires hamn är aldrig i
köket. Han klättrar upp i masten varifrån han
under stundom utstöter lyriska haranger som
får självaste Storfåglarna att sluta skräna, om
än bara till dess att romen tagit slut och Poeten
från Buenos Aires hamn klättrar ned igen.

= Dag 33

Vi får se hur det går med ekonomien, eller
budgeten, jag har inte så bra koll på de där
aktiebolagsmässiga termerna som Nils Langlet
så hett eftertraktar till sin ärvda Tråleria.

Här är istället en lista över trålade prylar:

' Den blå tunnan från Half-Life 2.

- Skogspornograä! Nostalgitripp på trål! Glad.
- En drömklänning Margareta inte ville ha.

- En uppsättning möjligtvis antika knappar.

- Ett paket fiskpinnar, bortanför bäst-före.

- En bok om astrologi och N ordstjärnan.

- Karta över Örebro, Förvaltningarnas stad.

= Dag 34

Vi passerade en sådan bastuflotte. Nils talade
länge och väl med deras "kapten”, som han
demonstrativt gestikulerade citationstecknen
efteråt, och berättade att enligt änska
Statistikcentralen dör varje år mellan 30 och
40 änländare medan de badar bastu. Det är
fler än för några årtionden sedan. Och de
undrar hur ett land med världens högsta
självmordsandel, i konkurrens med Litauen,
samtidigt, till skillnad från Litauen, kan rankas
som världens lyckligaste folk. Det är väl ändå
logiskt, det förstår till och med djupingen från
Buenos Aires hamn. Mary, är du från Finland?

= Dag 35

Funderar fortfarande på tanden. Tänder som
är munhålans skyltfönster och insiktsskydd.
Näst intill omöjligt att se någon nyglugg bland
besättningen med de rådande sura minerna.

Jag anser att Larsson å det grundligaste har
missförstått det här med trålande. Langlet är
däremot en sann Trålkarl.

Så här ylade poeten mot månen i natt: "Åh du
efterhängsna skugga/ Dig känner jag inte igen/
Det är som att du bär/ på ett mått av sol/ som
jag inte kan känna när] du är här/ som du är.”

= Dag 36

Dimma. Jag tänker på tanken. Är det bensin
som tar oss an horisonten? Eller diesel; svavel;
kaminer; vad vet jag! Människan är en
främling i världen, och jag är en främling på
trålen som är hela min värld. Jag vill härifrån
men vågar inte säga något, de andra bara
skrotar runt och under stundom rycker Kapten
Langlet fram sin pipa med en långsam rörelse,
Vilket talar sitt tydliga språk då en sådan
rörelse inte är ryckig -jag upplever saker
intensivare, snabbare, mer våldsamma än de
kanske är, bara för att jag är så rädd för vad
som ska bli av oss.

= Dag 37

Vi får inte slå av på takten. En träl färdas
genom vågorna, mot horisonten. Det är allt jag
behöver veta för att bli nöjd, tydligen. Poeten
påpekade: en för oss väsensfrämmande typ av
materia, kallad vatten, som utgör havet, liksom
våra köttkroppar, farkoster för de dunder-
blixtrande nervsystem som sluter an till sort-
eringsapparaten känd som rörelsedetektorn på
savannen; detta vatten möter luften och
mittemellan, i den exakta brytpunkt som ingen
stilla stund låter sig deänieras ty vår trålare gör
kaos med solsystemets tilltänkta tystnad, på en
ytai bubblan som är vår grönblå planet.

= Dag 38

Vågor är nog den bästa metaforen, för mångt
och mycket. Just nu känner jag att vi är på väg
upp på det högsta vågkrönet hittills. Vad det
säger om mig vågar jag inte säga.

Ena dagen är vi på väg till Liberia, nästa till
Nordnorge för att rädda en ubåt. "Ha trålamod,
vi kommer kunna ära mycket när ubåten är
räddad ur sitt djupa hål med våran starka trål,
vi män av st' ”, säger kapten.

= Dag 39

Världsankaret har oss i sitt grepp som Larssons
äskelina slår in hemska spetsliknande
aluminiumkrokar i äskarnas käft, ett köttsligt
grepp om en annan typ av känsel; poeten
upplever sällsam spänst i de äskespö som satts
samman av trållina och drucken champisburk.

Jag undrar: Om de vi räddar inte underkastar
sig arbets- och rummykulturen här på trålen.
Har alla i besättningen frikort att vrida deras
armar i tusen trålar då? Det gör ju ont som
tusan. Förväntar de sig gratis sprite? Vi har
mer av en champiskultur här, ju.

= Dag 40

Belgare såg vi idag. Hälsade inte tillbaka. Vi
alltså. Fort ska det gå, innan världsisen
återvänder, den som ödelade allt fast tvärtom,
liksom stängde bubblan av luft. Förutom
Atlantis då. Jag har inte en aning om Atlantis
säger poeten, och då säger jag att Larsson inte
har en susning om någonting, när vi spelar
rummy, och då säger rummy-dealern åt oss att
visa korten. Jag vill att Mary ska visa brösten.

Ny dag, nya lärdomar. För att inte använda
egna ord: "Fira betyder inte fest! Vi ska ta ned
segelvimpeln ur trålarmasten!"

= Dag 41

Det är så fruktansvärt härligt att bälga i sig en
butelj eller två, det håller till och med Larsson
med om.

Larsson är en urusel poet.

Margareta tyckte om mina ord så mycket att
hon slickade sig om öronen, så att säga. Jag
undrar hur det skulle kännas att ha Margaretas
tunga i mitt öra. Eller liksom mot örat, kring
örat, hur det vore om hon behandlade mitt öra
som en ungmö med mjuk hud behandlar ett
körsbäri en erotisk novell.

= Dag 42

Är det torsdag? Precis som när det gäller
många andra veckodagar, har jag inte en
susning längre. De är ju döpta efter nordisk
mytologi, till exempel fredag, onsdag. Jag
tycker om onsdagar. Men tisdagar är inte fy
skam det heller. Det har jag alltid gjort. Det har
de aldrig varit. Jag slår vad om att poeten
tycker om måndagar, och Larsson gillar säkert
söndagar på ren pin kiv, medan Langlet känns
som att han står över allt sånt där. Han förlorar
aldrig ett rummyparti.

= Dag 43

Sedan

dagarna två

har jag

varit

spik
-nykter.

Hur ska jag kunna förklara det för Margareta
utan att Larsson lägger sig i.

Tiden går långsamt.

= Dag 44

Jag glömde bort att berätta om det mest
intressanta fyndet i gårdagens trålrapport.
Men det var för att jag inte äck se det, ty
fyndets värde överskred min skeppargrad. Det
var en kristall... Kanske blir vi rika nu? Jag får
inget veta men är glad att vi gjort ett fynd som
kanske gör Mary glad. Jag suktar även efter
baugetter, mjuka som leendet på flickan jag
dansade rumba med i natt, hennes höfter
böljande som självaste havet, och jag
skälvande som denna trål vid händelse av
storm, maktlös inför den mäktiga poesidons
nyckfulla rättvisa!

= Dag 45

Om trälar kunde flyga
så skulle jag vilja
landa

i Serbien.

= Dag 46

Jag hör tydligen bättre hemma på en
optimistj olle, har jag förstått. Då hade jag
åtminstone kunnat styra själv, för på en sådan
änns bara plats för en person när man är så
"svanfet” som jag. Försöker låta alla pikar
rinna av mig som vatten från en gås, men det
är svårt att inte förgås av bitterhet, när man
sakta förgås här på havet som slukar drömmar
likt himlen sväljer döda stjärnors ljus när den
inte är mörk nog i en genomsnittlig stad eller
molnen sveper fram från Kina ovan vår
gränsupplösande trans-Atlant.

= Dag 47

Läser en bok jag inte har läst. Hoppas jag får
ha den för mig själv. På en trål får man inte ha
mycket för sig själv.

Ibland ryker det, och lik-
som sjuder, ett tvivels-

undanröjande pipande,
ur kaptenens topplock.

= Dag 48

"Begreppet lammkött om unga tjejer är äldre
än 2700 år.” Så talade kaptenen.

"Jag skiter i var vi är, jag går av.” Det var
beskedet från kaptenen.

= Dag 49

Nu sitter vi här. Jag vågar inte lämna trålen.

Tunna tunna jag

räddad ur ett folkhav

hämtad ur djupets yta av en pråm

nu dansar drömmarna rumba på en trål
enbart kvar ett halvt ben

en dag blir han stolt, min kapten

= Dag 50

Nils Langlet ramlade in i går. Det var
fruktansvärt nära skeppsbrott trots att vi låg i
hamn. Men han verkar ha fått ny energi av
uppbrottet, avbrottet från oss odugliga
skeppare, och Margareta. Det första som hände
var att Larsson äck en kram.

Jag har inte känt någon annans hud mot min
på femtio dagar.

= Dag 51

Rummy-dealern gav mig, med en insiktsfullt
riktad och till synes menande blick, en
broschyr om Sjöfartsförsäkringsbolag. Jag vill
gärna ställa allt till rätta, och så klart, få betalt,
i något annat än äsk.

 
= Dag 52

Vi kommer inte att åka till Acapulco, hur
mycket jag än tjatar om det. Albert dock änns i
samma Liverpool som Europas äldsta
kinesiska community, som kom i samband
med att undervattentunneln byggdes på
artonhundratalet, vilket en kan förmoda
krävde sin ingenjörskonst. Är det dit
Världsankaret söker sin botten nu? Jag hade
gärna ätit kött med glaze, på det väl avmätta
sättet asiatisk matkonst tenderar att visa
världen att man inte behöver Sås I Mängder för
att dämpa sin orala fixering. Ursäkta, jag har
regresserä till max fem års ålder. ”Hopplös.”

= ag 53

Fiddler's Green ("spelemans äng");
sjömännens avtalsenliga yrkesparadis när de
råkat törna in för gott. Där änns ett överflöd av
livets goda; galanta damer att ta en svängom
med bland prunkande träd som bågnar av
färdigbuteljerade frukter, vilka som omväxling
serveras av jordelivets befälhavare.

Trålrapport:
- Ett smaragdanstruket silverskirnrande skelett

= Dag 54

En trålare är inte som vilket fartyg som helst,
och även om det är vatten som omsluter vår
planet innebär det inte att alla vatten är
desamma. Det förstod jag av kaptenens
grymtande. Jag önskar jag var bättre på att
skrota runt.
Kortspelet
rummy - det
är inget för

en dummy! : '

 
= Dag 56

I dag äck jag lära mig ett nytt ord på arabiska
som jag av respekt inte kommer att skriva här.
Det är som att saker och ting svävar i en
tyngdlös rymd, därunder vattenytan, dit ingen
människa och bara, bara vår trål når.

Trålrapport:

- Kravmärkt sparkcykel

- ABBA-vinyl

- Tub med Wilson tennisbollar
- Bok om svunna tider. Oläsbar.
- Isterband.

- Flugäskedrag.

= Dag 57

Jag har glömt att berätta vilka som är på trålen.
Först och främst har vi Larsson.
Sedan Nils, det är hans trål.
Och jag. Råttoma. Storfåglarna.

Har Margareta klivit av? Eller var det en dröm
när hon klev på. Mary som jag kallar henne.

Rummy-dealern.

= Dag 58

Alla hamnar är inte likadana. Det änns vissa
som befolkas av vänner, men det är inte alla
som behandlar vännerna som sådana. Det går
skrönor — eller verkliga myter — om personer
som Väntar på att få hjälpa till att göra
besättningen fri från pant, och i något av alla
tillfällens gengäld kanske bjuda på en flaska
eller en dikt. Det är sådana som behövs i våra
hamnar, understryker kapten, och berättar om
vissa ovänskapliga som kommit att finna sig
ivägsparkade vid händelse av inkräktande på
socialt berättigat territorium. Länge leve
hamnens hjältar, suckade kapten innan sömn.

= Dag 59

Postbojen;

företeelse med angiven position mitti
Gibraltarsund och en del andra farleder, viktig
för nyblivna sjömän som före passagen
uppmanas att skynda sig att skriva färdigt
breven hem till tjejen eller till mor och far.
Verklighetsbakgrund utgör Post Ofäce Bay på
Charles Island, numera Floreana, som är en av
Galapagosöarna. Där änns sedan slutet av
1700-talet en posttunna. Valfångare och
säljägare lade sina privatbrev där, varpå
hemgående skepp tömde tunnan och tog med
breven upp till USA eller Europa.

= Dag 60

Varför? Jo! Det vet jag. Jag ville innan, så det
intalar jag mig nu också. Vilja är någonting
som är svårt att förstå sig på, ergo, att kunna
redogöra för i så här svepande lediga termer
vilket passar dagbokens korta kliniska
rapporterande, livsbringande format. Men för
att kasta lite sken över fenomenet är det ju så
att det har skrivits otaliga böcker om ämnet,
och de som har skrivit böcker om annat, har
ofta gjort det av sin vilja. Det är en vacker
tanke, att jag inte är tvingad att skriva det här,
av annat än min vilja. Min vilja är min vilja och
det skulle jag inte vilja ändra på. Ha!

= Dag 61

Larsson! Vi hittade honom djupt inne, bakom
kylrummet. Försökte urskulda sig med att han
planterat råttgift, men sedermera blev vi varse,
likt hur kaviar trycks ur en tub, att han hade
tagit sig friheten att bygga sig en hörna som
såg ut som äskedamm blandat med sharnan—
konvent. Vad fanns i påsarna? Det vet bara
kapten, antagligen Margareta (mina drömmars
Mary) och förhoppningsvis Larsson.

Ingenting förvånar mig längre. I går frågade
Rummy-dealern mig om jag eller för den delen
trålen var försäkrad. Jag hajade till.

= Dag 62

".....

......"

Jag kan inte morse. Försökte jag på morse
signalera till de som blippade åt mig på radion.

"Katastrof”, röt kapten. Nu måste vi rädda ett
till fartyg.

= Dag 63

Nils är klapp kanon. Eller är det jag som
förlorat fotfästet, slagit i örat? Känner hur
världen gungar under mina fötter, på det
diametralt motsatta sätt som Världsankaret
vajar, vajar, vajar fram som vi plöjer fram med
vår trål på färd mot nästa hamn.

Tvingades spela rummy igen. Det var så det
urartade. Jag hör hur det nuppas. Måtte inte
Margareta bli besudlad av Larsson. Min
Margareta, min ryska kaviar i Behrings hav,
min hj ärtesnäcka vari drömmande matrosöra
kan höra Världsankarets hav ändas som moln.

= Dag 64

Åtgärd krävs, har det blinkat innanför mitt
pannben. Jag drog i ena örsnibben för att
kvittera meddelandet. Skjuta upp, skjuta till
något mer som man måste beta av.

Nu bloppar det i faxen:
JA G H ö R AV M 1 G

= Dag 65

Skuff är ett kul ord. Det tänker jag på efter att
ha fått höra visdomsorden från Ikaros, de
svenska tryckarklassikerna, förtäljda ur
kaptenens mun: Ingen älskar ett barn som inte
lyckas. Med de orden kom rummyn till sin
naturliga konklusion, och jag gick "hem till
mig” och skrev dagbok med ord, de enda som
kan förstå mig.

Till havs änns inga ord sägs det. Det vill jag
ändra på. Kanske om jag slänger dagboken
överbord, att någon kommer att äska upp
dem.

= ag 66

Sextiosex, och kexen är slut. "Kexen”. Falu
Rågrut brutna i små havrefrasliknande rutor,
utan fraset, smaken eller det inkluderade
välbeännandet. Idag har jag testat tanken som
en fågel mot ett fönster, om jag skulle tagit ett
jobb på Volvo istället. Mina tankars ström är
som ett rullband varvid jag står och grejar,
donar, för att kunna hushålla min kropps
existens här i världen, vad den nu har att
uträttai de sociala sammanhang man dras in
i. Samtidigt är jag till havs, i det stora blå, med
drömmar stora som himlen, och på jakt efter
en horisont som är vackrare än Mary, nästan.

= Dag 67

Att göra:

Grundmåla i fören.

Riv ner Larssons svinstia.

Läs om sjöfartsförsäkringarna, på grund av
situationen i verkligheten, med ekonomien
och budgeten.

I natt låg jag och sov när jag väckte av ett dunk.
Rusade ut och möttes i stegen upp till däck av
kapten som sa åt mig att lägga mig igen. Det
var bara "en tom tunna” som stötte in i oss. Det
är "sånt som händer” och inget jag ska bry mig
om.

= Dag 68

Hur många Larssons behövs det för att göra

mig skogstokig, så att säga, topp tunnor
rasande?

Låt mig omformulera.
För att jag ska bli skogstokig eller som man
säger ibland, topp tunnor rasande - hur många

Larsson behövs det då?

Ett kukharn av svandiarré-kaliber.

= Dag 69

Saker och ting sätts i ett särskilt sällsamt
perspektiv av att preja fram genom vattnets
brytbara genomskinliga yta, jag kan inte riktigt
sätta tån på det, det änns ett varsel om
uppsägningar och storkrig runt krönet, för vi
färdas uppåt, känns det som, jorden är en
uppförsbacke. Kan vi inte åka längsmed
rotationsaxeln i stället, undrar jag? Larsson.

= Dag 70

Bottnen slukar allt, enligt Kapten Langlet.

Trålrapport:

- En vinyl av Vikingarna: "Kramgoa låtar”

- En runsten på arabiska

' Köttbullar från Mellanöstern

' Jultomten från Tyskland

- Ali-miniumfolie från kebabrulle

- N eandertalarskelett, svart (av bottenslam)
- Mentometerknappar, obrukbara

- En hink, rostig, med ett rejält bettmärke

= Dag 71

Vad är det för liv jag lever, undrar Nils. Larsson
och Margareta. Jag tror att de har trekant nu.
Jag vet vilket liv jag lever. Den fria radikalen

i det förgrymmade paradigmskiftet som aldrig
kommer.

= Dag 72

I dag har jag lärt mig ett nytt ord.

Pisstofflor;

orientaliska gummitofflor med snodd mellan
stortån och den närmaste granntån. "Att ha
ställt pisstofflorna" är en eufemism —
förskönande omskrivning — för att ha gått över
suden, dvs hoppat överbord, på utsidan.

= Dag 73

Det var som en dröm. Vaknade och trodde att
rosten skulle prägla dagen, som vanligt. Att
Nils skulle vara butter, på Adam över radio,
som vanligt. Att döma av min förvåning var det
som en dröm: ankaret var skinande rent, som
silvermånen om nätternai Behrings sund.
Men också det var en del i alla vågor av
drömmar, det Visste jag, sarnmanbiten i
Mälaren. Jag kände Hurtigrutten bolma inom
mina katakomber som en biogasbuss i
Klarabergstunneln. Livet vänder! Livet vände.
Jag visste bara inte hur, som i en dröm.

= Dag 74

I dag har jag lärt mig ett nytt ord.
Kortmanshyra;

när de kvarvarande drabbades av merarbete
kunde de få dela på akterseglads hyra.

= Dag 75

Se vad som händer, mina
landsfränder och fjärran
karossvänner, när det ej
längre går att se var gränsen
går mellan det som hände igår
och var vi än vänder nu

går Gränges bränder

och änders tänder i lås.

= Dag 76

Margareta, din hud är som gassande hetta över
en asfaltsbelagd gatai nordöstra Spanien
hundratals år efter inbördeskriget; en drömsk
framtid. Larsson, din nuna är surare än en
ilsken animekaraktär... kan du inte bara flyga
åt fanders, flytta till Japan för fan!
 
= Dag 77

En oljetanker får inte vem som helst jobb på.
Det är som att en skeppare inte är en matros,
som inte är en kapten. Det änns skillnader,
divisioner — kaptenen har till och med slängt
sig i ordalag om dimensioner av kunskap som
skiljer trålfarare åt. Och där beänner jag mig
någonstans och skvalpar i Mälaren.

= Dag 78

Jag hörde kapten skratta högt — eller gråta

— inifrån sin hytt. Ett ord gick att urskilja från
allt stönande som antingen kom av sexande
eller en intim stund med sig själv på ett andligt
plan. Det var följande: "Knullkristallen".

Jag tittar på en akvarell jag fann i ryggsäcken
från senaste landstigningen. Det är en bild av
en apa med peruk och stilettklackar, samt
andra kvinnliga underkläder. Och jag som bad
om ett porträtt. Det är sista gången jag följer
Larssons råd om "goda gatukonstnärer”.
Dag 79

Trålrapport:

- Ett blandband
- En guide till Berlin av Carl-Johan Vallgren
- Ett flashminne med crackat material

' Ett påskris, antagligen från en bastuflotte
- En AR—lS-attrapp

- En kartong galgar, 1/7-del Domus

- En skyltdocka, med inbyggt kön
- En sjunken flaskpost

- Ett hundra kilo sjögräs
- Ett manskaps moral

  
= Dag 80

I vrån som en gång anggjordes till äskedamm
snubblade jag in härom kvällen, och begravde
ansiktet med ansiktet först ned i — inte golvet,
utan i kadavren från Storfåglarna som så länge
gäckade oss och höll poeten sällskap i masten.

Jag trodde vi fraktade äsk, men de hade ätits
upp av fåglarna. Som nu har ätits upp — av?
Dag 81

"AKTAS” stod det på de röda lapparna som slets
bort i ett ritsch av Margareta idag. Om det inte
vore för min goda anteckningsförmåga hade
nog bortslitningen av lapparna gått i glömska.
Nu änns akten dokumenterad här ovan. Jag
släpper dig aldrig, min Gäry Märy. Brukar dock
sällan gå tillbaka varken i reell tid, karriär eller
anteckningsböcker. Gjort är gjort och det är
också det äna i att komma framåt. Skulle
skummet bakom trålen inte spraka vilt så
skulle vi inte komma någon vart heller.

= Dag 82

Jag hade en mafäg dröm. En varelse, en man,
knappt en människa, en taskig ursäkt till i så
fall, driftade omkring på öppet hav — i en
tunna.

= Dag 83

Jag pratade om drömmen i dag och blev minst
sagt överraskad, inte av att Larsson kämpade
emot men av vad han övertygade mig om,
nämligen att jag har blivit — inte vansinnig,
men senildement, alternativt börjat förtränga
jobbiga saker, ty drömmen var så att säga
verklig; en man med en tunna som farkost, till
synes förlist från en sjunken oljetanker, hade
blivit upplockad av oss?! Otroligt, vi räddar folk
till höger och vänster. Nu i Atlanten.

Vad gjorde den mannen mot mig? Det har
faktiskt ömmati min akter ett tag.

= Dag 84

Kaptenen hade fått en bild, en än gåva från
Jean-Jaques i tunnan — vi har tydligen fångats
på bild från ovan. Jag frågade Nils om J-J skulle
vara med på rummyn ikväll. Fick inget
svar på min önskan att få umgås med
nykomlingen. Jag , börjar faktiskt tvivla
— änns han?

 
   
    


= Dag 85

Är månen under vattenytan eller ser det bara
ut som det? Åker egentligen vi upp och ner,
under ytan? En spegling av rotationen som blir
när vi åker på insidan av ytspänningen, upp
och ner, 360 grader runt jorden — inverterat!
Det trodde nog ingen i min familj skulle
hända, innan jag sa att jag gått och blivit vän
med Nils Langlet.

= Dag 86
Nytt bloppande fax, rykande hett ur hjärnan:
Mitt band Medusas Fruar ska på turné i södra
Sverige med våra klasskompisar i Heavy Waves
och vi ska änansiera det.
Stötta kvinnor och icke-binära på musikscenen
eller bara mig om ni skiter i det o skänk en
slant.

Swisha så snart jag kommit i land. Tack.

Obs. Har nytt nummer!

= Dag 87

Vem pratar Larsson med? Har jag klivit ur min
kropp, in i hans skuff, och inlett ett samtal?
Sitter jag inte här och skriver? Är det jag som
ÄR Larsson?

Har inte känt mänsklig hudkontakt på

87 dagar. Åh Margareta, rädda mig från
vansinnet i min kropp, jag flyr den som osunda
tankar osar ut ur Larssons knopp. Du skulle
alltid vara min Mary om du bara ville det, kliv
ur mina drömmars värld och gör mig verklig,
det sjuder lavai mitt bröst som vill explodera
och hindra flygplanen från att hota klimatet!

= Dag 88

Hallå var är jag.
Jag har tappat bort
min ip-adress men
om ni skiter i det
får ni gärna stötta
mig och följa mig

i ur och skur på
andra sätt, min
stralkropp
teränns
ågonstans mellan
kropolis, Aten och

Långtbortistan.

H>=momm

= Dag 89

Jag ska tråla dig
genom eld och vatten,
sila spigg och stim!

= Dag 90

Jag har blivit klokare. Larsson ljög, men hade
rätt. Jag har nu mött personen i tunnan jag
drömde om. en stor orange plåttunna med
några få små hål som man kan titta ut igenom
inklusive ett hål i botten för att titta ned, äck
jag berättat för mig ur hans mun — som han
bogseras här bakom oss. Jean-Jaques hade
bara stigit ombord för en kvick omgång
rummy. 122 dagar hade han färdats i tunnan.
I den hade han påträffat fartyg utan att vilja
ombordstiga — förrän han stötte in i vår trål.
Det var uppenbarelsen av vår kapten, Nils
Langlet, som äck honom att ge upp sina ideal.

= Dag 91

Livet är till

för att tråla.

    
= Dag 92

strålande!
Dag 93

Finskoma, våning fem, åk ej hem!
Det är ni, som får trålen, att gå ru-hunt!

= Dag 94

Det börjar bli fullt på fartyget. Nästan
ingenting får plats längre. När jag räknar upp
vad som änns ombord, inklusive besättning,
blir det mycket mindre än vad jag ser.

= Dag 95

Livet är till för att tråla.

= Dag 96

Råttboet hade kunnat bli vår undergång. Men
tack vare glatt humör och samarbetsvillighet är
kontraktet underskrivet och änanserna för
nästa långkok i hamn.

Och nu säger Nils så här:

Som Strindberg skrev: Sjöfartsförsäkrings-
bolaget Triton är världens mest moraliska
aktiebolag.

= Dag 97

Trålrapport:

- En störtad luftballong. Vet inte om den störtat
elller dumpats men i havet fanns den, med ett
hål i sig. Kanske var det Larssons
champis-krok som gjorde hålet, som annars
tyder på pyspunka.

= Dag 98

98 dagar av trålande. Minst. Men inte för
Larsson, för han ska bli styrelseledamot

i Triton och där fördelaktigt spjuvra å

Familj eföretaget Trålerians Trålkarlars vägnar,
med hopp om ekonomisk-moraliska
landvinningar för hela planeten. Vi ärade av
honom igår med ett rackarns galej, där
tonäskburkarna äntligen öppnades. Satan vad
gott det var! Sedan ett parti sjukortsrummy för
att verkligen understryka den festliga nyheten.
Sedan lämnade vi av honom hos en taxibåt
under känslosamma former. I mörkret. Sedan
somnade jag snabbt, jag var så plakat.
 
= Dag 100

Nils Langlet ramlade i igår. Vi har snurrat runt
här, mitt i Mälaren, i hundra dagar. Och nu
snurrar Nils Langlets lik runt trålen, som vore
han och Världsankaret ett. Känns som att vara
mitt i en galax — mitt i proppen i badkaret.

Jag älskar det.

= 100 dagar av trålande
— minst!
